version: '3.2'

services:

  bot:
    build: .
    volumes:
      - ./:/application
    command: ["npm","run","dev"]
    environment:
      - TOKEN=$TOKEN
      - URL_API=$URL_API
      - URL_SOCKETIO=$URL_SOCKETIO
