version: '3.2'

services:

  bot:
    build: .
    volumes:
      - ./:/application
    command: ["npm","run","dev"]
    environment:
      - TOKEN=OTA2OTg3Nzg2NzAyMjk1MTEy.YYgoMw.NO64jWk1AFSvG_iZxgz6qgqDzMg
